version: '3'
services:
  router:
    build: ./router
    ports:
      - "8080:8080"
    depends_on:
      - login
  login:
    build: ./login
    ports:
      - "8010:8080"
  register:
    build: ./register
    ports:
      - "8011:80"
